app_name = "Mauscribe"
version = "0.7.0"
volume_reduction_factor = 0.4
language = "de"

[logging]
level = "DEBUG"

[audio]
language = "de"
model = "small"
volume_reduction_factor = 0.4

[ui]
dark_mode = true
auto_start_gui = false
close_app_on_gui_close = false
enable_audio_files_tab = false
enable_audio_database = false
enable_enhanced_mode = false

[ui.notifications]
toast_duration = 1000

[ui.notifications.transcription_success]
toast = true
sound = true

[ui.notifications.recording_start]
toast = true
sound = true

[ui.notifications.recording_stop]
toast = true
sound = true

[ui.notifications.recording_error]
toast = true
sound = true

[ui.notifications.transcription_error]
toast = true
sound = true

[ui.notifications.transcription_empty]
toast = true
sound = true

[ui.notifications.text_inserted]
toast = true
sound = true

[ui.notifications.text_insert_error]
toast = true
sound = true

[ui.notifications.app_start]
toast = true
sound = true

[ui.notifications.app_shutdown]
toast = true
sound = true
