[transcription]
model = "small"
language = "de"

[system]
volume_reduction_factor = 0.4

[notifications]
sound = true
toast = true

[ui]
icon_path = "icons/icon.png"

[input.primary]
name = "x2"
type = "click"

[input.secondary]
name = "left"
type = "hold"
